### ISSUE TITLE
Data leakage

### ISSUE THREAD

**Issue by changyi7231** [Akirato/LLM-KG-Reasoning#2]
In Line 85 to Line 107 of generate_llm_questions.py, the entity_triplets and relation_triplets include the triplets of the test set, which leads  to data leakage. See Paragraph 4.1 of Query2Box for details.

**Comment by AI-Santiago** [comment]
> In Line 85 to Line 107 of generate_llm_questions.py, the entity_triplets and relation_triplets include the triplets of the test set, which leads to data leakage. See Paragraph 4.1 of Query2Box for details.

The q2b results given in the paper are higher than those in the original paper. Perhaps the author has considered this when evaluating the q2b method?

**Comment by changyi7231** [comment]
> > In Line 85 to Line 107 of generate_llm_questions.py, the entity_triplets and relation_triplets include the triplets of the test set, which leads to data leakage. See Paragraph 4.1 of Query2Box for details.
> 
> The q2b results given in the paper are higher than those in the original paper. Perhaps the author has considered this when evaluating the q2b method?

The q2b results are taken from "Beta Embeddings for Multi-Hop Logical Reasoning in Knowledge Graphs". The authors do not consider this problem.

**Comment by Akirato** [comment]
Hello,
Thanks a lot for your interest in the repo. The problem we are evaluating is not exactly similar to the traditional KG reasoning setup. We do think that LLMs are not capable of inferring relations (at least not as well as Q2B, etc.).
However, the primary evaluation is whether the KGs will be able to even reason the complex query given all the necessary context. Hence, all the necessary KG context needs to given to the model and we evaluate if the LLMs are able to parse the complex query to come up with reasonable answers.

**Comment by lazyloafer** [comment]
> > > In Line 85 to Line 107 of generate_llm_questions.py, the entity_triplets and relation_triplets include the triplets of the test set, which leads to data leakage. See Paragraph 4.1 of Query2Box for details.
> > 
> > 
> > The q2b results given in the paper are higher than those in the original paper. Perhaps the author has considered this when evaluating the q2b method?
> 
> The q2b results are taken from "Beta Embeddings for Multi-Hop Logical Reasoning in Knowledge Graphs". The authors do not consider this problem.

The test datasets are different between q2b and betaE, checking the "easy answers" and "hard answers" in 2p, 3p, 2i, 3i......
In addition, the evaluation codes in q2b and betaE are also different, q2b ranks "hard answers" and "negative answers", while betaE ranks "hard answers" and "easy answers". Orz
